### DISCUSSION TITLE
Data Model

### DISCUSSION THREAD

**Discussion by david-wolgemuth** [tijanisylla/guitar-shop#7] [General]
```yaml
guitars:
- id: 24
  model_name: "Stratocaster"
  description: "Instantly, totally familiar but subtly different, the American Pro II Strat is one of the most versatile electric guitars you're likely to play. Fender may well have created a new standard in production guitars with this one. "
  brand_name: "Fender"
  price: "1600.00"
  rating: 5
  image_url: "https://media.musiciansfriend.com/is/image/MMGS7/American-Professional-II-Stratocaster-Rosewood-Fingerboard-Electric-Guitar-3-Color-Sunburst/L78030000001000-00-500x500.jpg"
- id: 25
  model_name: "Stratocaster"
  description: "Instantly, totally familiar but subtly different, the American Pro II Strat is one of the most versatile electric guitars you're likely to play. Fender may well have created a new standard in production guitars with this one. "
  brand_name: "Fender"
  price: "1600.00"
  rating: 5
  image_url: "https://media.musiciansfriend.com/is/image/MMGS7/American-Professional-II-Stratocaster-Rosewood-Fingerboard-Electric-Guitar-3-Color-Sunburst/L78030000001000-00-500x500.jpg"

users:
- id: 6
  username: "joey64"
  password: "< secured >"
  role: "admin"

guitar_images:
- id: 4
  guitar_id: 24 
  url: "https:// ...."
- id: 5
  guitar_id: 24 
  url: "https:// ...."
```

for initial features, we can have the backend return a hard-coded JSON file  (or simply store it on the frontend)
